drop table if exists book;

CREATE TABLE book
(
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author VARCHAR NOT NULL,
    title  VARCHAR NOT NULL,
    year   INT CHECK (year >= 1000 AND year <= 3000)
);

INSERT INTO book(author, title, year)
VALUES ('George Orwell', '1984', 1948);
INSERT INTO book(author, title, year)
VALUES ('William Shakespeare', 'Hamlet', 1601);
INSERT INTO book(author, title, year)
VALUES ('Ernest Hemingway', 'The Old Man and the Sea', 1952);

SELECT * FROM book ORDER BY id;